name: "Gemini AI Code Reviewer"
description: "This GitHub Action automatically reviews PRs using Google's Gemini AI model."
author: 'truongnh1992'
branding:
  icon: 'zoom-in'
  color: 'blue'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token to interact with the repository'
    required: true
  GEMINI_API_KEY:
    description: 'Google Gemini API key'
    required: true
  GEMINI_MODEL:
    description: 'The Gemini model to use for code review'
    required: false
    default: 'gemini-2.5-flash'
  EXCLUDE:
    description: 'Comma-separated list of file patterns to exclude'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install google-generativeai PyGithub unidiff google-ai-generativelanguage==0.6.10 github3.py==1.3.0 tenacity>=8.0.0

    - name: Run code review
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GEMINI_API_KEY: ${{ inputs.GEMINI_API_KEY }}
        GEMINI_MODEL: ${{ inputs.GEMINI_MODEL }}
        EXCLUDE: ${{ inputs.EXCLUDE }}
      run: python ${{ github.action_path }}/review_code_gemini.py
