name: "Claude Code Reviewer"
description: "This GitHub Action automatically reviews PRs using Anthropic's Claude 3.5 Sonnet model."
author: 'truongnh1992'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token to interact with the repository'
    required: true
  ANTHROPIC_API_KEY:
    description: 'Anthropic API key'
    required: true
  CLAUDE_MODEL:
    description: 'The Claude model to use for code review'
    required: false
    default: 'claude-3-5-sonnet-20240620'
  INPUT_EXCLUDE:
    description: 'Comma-separated list of file patterns to exclude'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install anthropic>=0.18.0 PyGithub unidiff requests github3.py==1.3.0

    - name: Run code review
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        ANTHROPIC_API_KEY: ${{ inputs.ANTHROPIC_API_KEY }}
        CLAUDE_MODEL: ${{ inputs.CLAUDE_MODEL }}
        INPUT_EXCLUDE: ${{ inputs.EXCLUDE }}
      run: python ${{ github.action_path }}/review_code_claude.py
