name: "OpenAI Code Reviewer"
description: "This GitHub Action automatically reviews PRs using OpenAI's GPT-3.5 Turbo model."
author: 'truongnh1992'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token to interact with the repository'
    required: true
  OPENAI_API_KEY:
    description: 'OpenAI API key'
    required: true
  OPENAI_MODEL:
    description: 'The OpenAI model to use for code review'
    required: false
    default: 'gpt-3.5-turbo'
  EXCLUDE:
    description: 'Comma-separated list of file patterns to exclude'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install openai==0.28.0 PyGithub unidiff requests github3.py==1.3.0

    - name: Run code review
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
        OPENAI_MODEL: ${{ inputs.OPENAI_MODEL }}
        EXCLUDE: ${{ inputs.EXCLUDE }}
      run: python ${{ github.action_path }}/review_code_openai.py